name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  - push
  - workflow_dispatch

env:
  EARTHLY_USE_INLINE_CACHE: true
  EARTHLY_SAVE_INLINE_CACHE: true
  EARTHLY_VERBOSE: true
  EARTHLY_FULL_TARGET: true
  EARTHLY_OUTPUT: true

jobs:
  set-version:
    name: Set variables
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: "Set version"
        id: constants
        run: |
          export version="$(date +%Y%m%d%H%M%S)-$(git describe --always --dirty --exclude '*')"
          echo "version=${version}"
          echo "version=${version}" >> ${GITHUB_OUTPUT}
    outputs:
      version: "${{ steps.constants.outputs.version }}"
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - set-version
    env:
      version: "${{ needs.set-version.outputs.version }}"
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and possibly push
        env:
          EARTHLY_PUSH: "${{ github.ref == 'refs/heads/main' }}"
          EARTHLY_ORG: ${{ vars.EARTHLY_ORG }}
          EARTHLY_SATELLITE: ${{ vars.EARTHLY_SATELLITE }}
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          earthly +build "--version=${version}"
      - name: Save executables for release
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: executable
          path: target/libpam_bitwarden.*
          if-no-files-found: error
  release-candidate:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - set-version
      - build
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: lee-dohm/close-matching-issues@e9e43aad2fa6f06a058cedfd8fb975fd93b56d8f # v2
        with:
          query: 'label:release-candidate'
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: dacbd/create-issue-action@cdb57ab6ff8862aa09fee2be6ba77a59581921c2 # v2.0.0
        name: Create Release candidate issue
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          title: Release candidate ${{ needs.set-version.outputs.version }}
          labels: release-candidate
          body: |
            A new release candidate has been created.
            Comment on this issue with `/approve-release` to promote this candidate to a full release.
            <details>
            <summary>Release candidate data</summary>
            ```
            version: ${{ needs.set-version.outputs.version }}
            run_id: ${{ github.run_id }}
            ```
            </details>
